# Assignment 4

In [1]:
#installing and importing libraries
!pip install selenium
from selenium import webdriver
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import bs4
from bs4 import BeautifulSoup
import requests

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: selenium in c:\users\lavina\appdata\roaming\python\python39\site-packages (4.7.2)
Requirement already satisfied: trio~=0.17 in c:\users\lavina\appdata\roaming\python\python39\site-packages (from selenium) (0.22.0)
Requirement already satisfied: urllib3[socks]~=1.26 in c:\programdata\anaconda3\lib\site-packages (from selenium) (1.26.11)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\lavina\appdata\roaming\python\python39\site-packages (from selenium) (0.9.2)
Requirement already satisfied: certifi>=2021.10.8 in c:\programdata\anaconda3\lib\site-packages (from selenium) (2022.9.14)
Requirement already satisfied: cffi>=1.14 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\lavina\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.0.4)
Requirement already satisfied: sniffio in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: idna in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: async-generator>=1.9 in c:\users\lavina\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: attrs>=19.2.0 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: sortedcontainers in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: outcome in c:\users\lavina\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\lavina\appdata\roaming\python\python39\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\programdata\anaconda3\lib\site-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\lavina\appdata\roaming\python\python39\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [2]:
# define a function to open an url
def given_url(url):
    global driver
    # first, connect to the webdriver
    driver=webdriver.Chrome(r'chromedriver.exe')
    # maximize window
    driver.maximize_window()
    #enter the url
    driver.get(url)
    delay=10

# 1. Scrape the details of most viewed videos on YouTube from Wikipedia from given URL

In [3]:
# give required URL
url= "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
# opening url
given_url(url)    
#creating a blank list to store required data
Rank=[]
Name=[]
Artist=[]
Upload_date=[]
Views=[]

In [4]:
#scraping rank from URL
try:
    rank=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[1]')
    for i in rank:
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("-")
Rank=Rank[0:30]
Rank

#scraping name from URL
try:
    name=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[2]')
    for i in name:
        Name.append(i.text)
except NoSuchElementException:
    Name.append("-")
    Name=Name[:-3]
    
#scraping artist from URL
try:
    artist=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[3]')
    for i in artist:
        Artist.append(i.text)
except NoSuchElementException:
    Artist.append("-")
    
#scraping upload date from URL
try:
    upload=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[5]')
    for i in upload:
        Upload_date.append(i.text)
except NoSuchElementException:
    Upload_date.append("-")
    
#scraping views from URL
try:
    views=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[4]')
    for i in views:
        Views.append(i.text)
except NoSuchElementException:
    Views.append("-")
    
# printing length
print(len(Rank),len(Name),len(Artist),len(Upload_date),len(Views))

30 30 30 30 30

In [5]:
#making dataframe
df=pd.DataFrame({'Rank':Rank,'Name':Name, 'Artist':Artist,'Upload date':Upload_date,'Views':Views})
df

,Rank,Name,Artist,Upload date,Views
0,1.,"""Baby Shark Dance""[4]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",12.00
1,2.,"""Despacito""[7]",Luis Fonsi,"January 12, 2017",8.05
2,3.,"""Johny Johny Yes Papa""[14]",LooLoo Kids,"October 8, 2016",6.57
3,4.,"""Bath Song""[15]",Cocomelon â€“ Nursery Rhymes,"May 2, 2018",5.89
4,5.,"""Shape of You""[16]",Ed Sheeran,"January 30, 2017",5.88
5,6.,"""See You Again""[18]",Wiz Khalifa,"April 6, 2015",5.74
6,7.,"""Phonics Song with Two Words""[23]",ChuChu TV,"March 6, 2014",5.08
7,8.,"""Uptown Funk""[24]",Mark Ronson,"November 19, 2014",4.79
8,9.,"""Wheels on the Bus""[25]",Cocomelon â€“ Nursery Rhymes,"May 24, 2018",4.77
9,10.,"""Learning Colors â€“ Colorful Eggs on a Farm""[26]",Miroshka TV,"February 27, 2018",4.76
10,11.,"""Gangnam Style""[27]",Psy,"July 15, 2012",4.64
11,12.,"""Masha and the Bear â€“ Recipe for Disaster""[32]",Get Movies,"January 31, 2012",4.52
12,13.,"""Dame Tu Cosita""[33]",El Chombo,"April 5, 2018",4.18
13,14.,"""Sugar""[34]",Maroon 5,"January 14, 2015",3.80
14,15.,"""Roar""[35]",Katy Perry,"September 5, 2013",3.70
15,16.,"""Counting Stars""[36]",OneRepublic,"May 31, 2013",3.70
16,17.,"""Axel F""[37]",Crazy Frog,"June 16, 2009",3.67
17,18.,"""Sorry""[38]",Justin Bieber,"October 22, 2015",3.62
18,19.,"""Thinking Out Loud""[39]",Ed Sheeran,"October 7, 2014",3.53
19,20.,"""Baa Baa Black Sheep""[40]",Cocomelon â€“ Nursery Rhymes,"June 25, 2018",3.46
20,21.,"""Dark Horse""[41]",Katy Perry,"February 20, 2014",3.42
21,22.,"""Waka Waka (This Time for Africa)""[42]",Shakira,"June 4, 2010",3.40
22,23.,"""Faded""[43]",Alan Walker,"December 3, 2015",3.38
23,24.,"""Let Her Go""[44]",Passenger,"July 25, 2012",3.36
24,25.,"""Girls Like You""[45]",Maroon 5,"May 31, 2018",3.35
25,26.,"""Perfect""[46]",Ed Sheeran,"November 9, 2017",3.33
26,27.,"""Bailando""[47]",Enrique Iglesias,"April 11, 2014",3.31
27,28.,"""Lean On""[48]",Major Lazer,"March 22, 2015",3.31
28,29.,"""Humpty the train on a fruits ride""[49]",Kiddiestv Hindi â€“ Nursery Rhymes & Kids Songs,"January 26, 2018",3.26
29,30.,"""Lakdi Ki Kathi""[50]",Jingle Toons,"June 14, 2018",3.24

In [11]:
driver.close()

# 2.Scrape the details team Indiaâ€™s international fixtures from bcci.tv.

In [10]:
# giving url
url= 'https://www.bcci.tv/'
# opening url
given_url(url)

In [12]:
# click on "menu" button to expand it
#btn=driver.find_element(By.XPATH,'//span[@class="menu-icon__line menu-icon__line-right"]')
#btn.click()

# click on "international" button to expand it
inter=driver.find_element(By.XPATH,'/html/body/nav/div[1]/div[2]/ul[1]/li[2]')
inter.click()

In [ ]:



# creating empty lists for scraping the data
Match_Title = []
Series = []
Place = []
Date = []
Time = []

#scraping match title
title=driver.find_elements(By.XPATH,'//h5[@class="fix-text"]')
for i in title:
    Match_Title.append(i.text)
    
#scraping series
series = driver.find_elements(By.XPATH,'//div[@class="fixture-card-mid d-flex align-items-center justify-content-between"]') 
for i in series:
    Series.append(i.text)
# scraping place
place=driver.find_elements(By.XPATH,'//span[@class="ng-binding ng-scope"]')
for i in place:
    Place.append(i.text)

#scraping time and date
time=driver.find_elements(By.XPATH,'//h5[@class="text-right ng-binding"]')
for i in time:
    Time.append(i.text)

date=driver.find_elements(By.XPATH,'//h5[@class="ng-binding"]')
for i in time:
    Date.append(i.text)

In [24]:
 Title=Match_Title[1::2]

In [27]:
#printing length
print(len(Title),len(Series),len(Place),len(Time),len(Date))

8 8 8 8 8

In [28]:
# creating data frame
df=pd.DataFrame({'Match Title': Title, "Series": Series,"Place": Place, "Date": date,"Time": Time})
df

,Match Title,Series,Place,Date,Time
0,INDIA WOMEN U19 TOUR OF SOUTH AFRICA WOMEN U19,India Women U19\nvs\nSouth Africa Women U19,"Steyn City School Ground,",<selenium.webdriver.remote.webelement.WebEleme...,5:15 PM IST
1,SRI LANKA TOUR OF INDIA T20 SERIES 2022-23,India\nvs\nSri Lanka,"Wankhede Stadium,",<selenium.webdriver.remote.webelement.WebEleme...,7:00 PM IST
2,INDIA WOMEN U19 TOUR OF SOUTH AFRICA WOMEN U19,India Women U19\nvs\nSouth Africa Women U19,"Steyn City School Ground,",<selenium.webdriver.remote.webelement.WebEleme...,1:30 PM IST
3,SRI LANKA TOUR OF INDIA T20 SERIES 2022-23,India\nvs\nSri Lanka,"Maharashtra Cricket Association Stadium,",<selenium.webdriver.remote.webelement.WebEleme...,7:00 PM IST
4,SRI LANKA TOUR OF INDIA T20 SERIES 2022-23,India\nvs\nSri Lanka,"Saurashtra Cricket Association Stadium,",<selenium.webdriver.remote.webelement.WebEleme...,7:00 PM IST
5,SRI LANKA TOUR OF INDIA ODI SERIES 2022-23,India\nvs\nSri Lanka,"Barsapara Cricket Stadium,",<selenium.webdriver.remote.webelement.WebEleme...,1:30 PM IST
6,SRI LANKA TOUR OF INDIA ODI SERIES 2022-23,India\nvs\nSri Lanka,"Eden Gardens,",<selenium.webdriver.remote.webelement.WebEleme...,1:30 PM IST
7,SRI LANKA TOUR OF INDIA ODI SERIES 2022-23,India\nvs\nSri Lanka,"Greenfield International Stadium,",<selenium.webdriver.remote.webelement.WebEleme...,1:30 PM IST

In [29]:
driver.close()

# 3.Scrape the details of selenium exception from guru99.com.

In [80]:
# giving url
url = 'https://www.guru99.com/'
# opening url
given_url(url)

In [81]:
#creating a blank list to store the scraped data
Name=[]
Description=[]

In [82]:
# clicking on Selenium button
selbut=driver.find_element(By.XPATH,'//li//a[@title="Selenium"]')
selbut.click()

# clicking on Exception Handling button
excp=driver.find_element(By.XPATH,'//a[@title="Selenium Exception Handling (Common Exceptions List)"]')
excp.click()

In [83]:
# scraping Name
name=driver.find_elements(By.XPATH,'/html/body/div[1]/div/div/div/main/div/article/div/div/p/strong')
for i in name:
    Name.append(i.text)

In [84]:
# scraping Description
des=driver.find_elements(By.XPATH,'/html/body/div[1]/div/div/div/main/div/article/div/div/p')
for i in des:
    Description.append(i.text)

In [104]:
Name=Name[:46]
Description=Description[0:46]
print(len(Description),len(Name))

46 46

In [105]:
#printing length
print(len(Name),len(Description))

    
# creating the dataframe from the scraped data
df = pd.DataFrame({'Name':Name,'Description':Description[0:47]})
df

46 46

,Name,Description
0,1. ElementNotVisibleException:,1. ElementNotVisibleException: This type of Se...
1,2. ElementNotSelectableException:,2. ElementNotSelectableException: This Seleniu...
2,3. NoSuchElementException:,3. NoSuchElementException: This Exception occu...
3,4. NoSuchFrameException:,4. NoSuchFrameException: This Exception occurs...
4,5. NoAlertPresentException:,5. NoAlertPresentException: This Exception occ...
5,6. NoSuchWindowException:,6. NoSuchWindowException: This Exception occur...
6,7. StaleElementReferenceException:,7. StaleElementReferenceException: This Seleni...
7,8. SessionNotFoundException:,8. SessionNotFoundException: The WebDriver is ...
8,9. TimeoutException:,9. TimeoutException: Thrown when there is not ...
9,10. WebDriverException:,10. WebDriverException: This Exception takes p...
10,11. ConnectionClosedException:,11. ConnectionClosedException: This type of Ex...
11,12. ElementClickInterceptedException:,12. ElementClickInterceptedException: The comm...
12,13. ElementNotInteractableException:,13. ElementNotInteractableException: This Sele...
13,14. ErrorInResponseException:,14. ErrorInResponseException: This happens whi...
14,15. ErrorHandler.UnknownServerException:,15. ErrorHandler.UnknownServerException: Excep...
15,16. ImeActivationFailedException:,16. ImeActivationFailedException: This expecta...
16,17. ImeNotAvailableException:,17. ImeNotAvailableException: It takes place w...
17,18. InsecureCertificateException:,18. InsecureCertificateException: Navigation m...
18,19. InvalidArgumentException:,19. InvalidArgumentException: It occurs when a...
19,20. InvalidCookieDomainException:,20. InvalidCookieDomainException: This happens...
20,21. InvalidCoordinatesException:,21. InvalidCoordinatesException: This type of ...
21,22. InvalidElementStateException:,22. InvalidElementStateException: It occurs wh...
22,23. InvalidSessionIdException:,23. InvalidSessionIdException: This Exception ...
23,24. InvalidSwitchToTargetException:,24. InvalidSwitchToTargetException: This occur...
24,25. JavascriptException:,25. JavascriptException: This issue occurs whi...
25,26. JsonException:,26. JsonException: It occurs when you afford t...
26,27. NoSuchAttributeException:,27. NoSuchAttributeException: This kind of Exc...
27,28. MoveTargetOutOfBoundsException:,28. MoveTargetOutOfBoundsException: It takes p...
28,29. NoSuchContextException:,29. NoSuchContextException: ContextAware does ...
29,30. NoSuchCookieException:,30. NoSuchCookieException: This Exception occu...
30,31. NotFoundException:,31. NotFoundException: This Exception is a sub...
31,32. RemoteDriverServerException:,32. RemoteDriverServerException: This Selenium...
32,33. ScreenshotException:,33. ScreenshotException: It is not possible to...
33,34. SessionNotCreatedException:,34. SessionNotCreatedException: It happens whe...
34,35. UnableToSetCookieException:,35. UnableToSetCookieException: This occurs if...
35,36. UnexpectedTagNameException:,36. UnexpectedTagNameException: Happens if a s...
36,37. UnhandledAlertException:,37. UnhandledAlertException: This expectation ...
37,38. UnexpectedAlertPresentException:,38. UnexpectedAlertPresentException: It occurs...
38,39. UnknownMethodException:,39. UnknownMethodException: This Exception hap...
39,40. UnreachableBrowserException:,40. UnreachableBrowserException: This Exceptio...
40,41. UnsupportedCommandException:,41. UnsupportedCommandException: This occurs w...
41,Step 1) Try-catch,"Here, are some important standard using which ..."
42,Catch,Step 1) Try-catch
43,Step 2) Multiple catch blocks,"This method can catch Exceptions, which uses a..."
44,Step 3) Throw,Step 2) Multiple catch blocks
45,Step 4) Multiple Exceptions,"There are various types of Exceptions, and you..."

In [ ]:
driver.close()

# 4. Scrape the details of State-wise GDP of India from statisticstime.com.

In [65]:
# giving URL
url= 'http://statisticstimes.com/'
# opening url
given_url(url)

In [ ]:
# clicking on Economy button
economy=driver.find_element(By.XPATH,'//div[@class="navbar"]/div[2]/button')
economy.click()

# clicking on India
india=driver.find_element(By.XPATH,'//div[@class="dropdown-content"]/a[3]')
india.click()


# clicking on GDP of Indian Economy
GDP = driver.find_element(By.XPATH,'//a[@class="ec"]')
GDP.click()
time.sleep(3)

# creating empty list
Rank = []
State = []
GSDP1 = []
GSDP2 = []
Share = []
GDP_billion = []

# scraping Rank
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("_")
    
# scraping State
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[2]"):
        State.append(i.text)
except NoSuchElementException:
    State.append("_")
    
# scraping GSDP at current price (19-20)
try:
    for i in driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[3]'):
        GSDP1.append(i.text)
except NoSuchElementException:
    GSDP1.append("_")
    
# scraping GSDP at current price (18-19)
try:
    for i in driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[4]'):
        GSDP2.append(i.text)
except NoSuchElementException:
    GSDP2.append("_")
    
# scraping Share (18-19)
try:
    for i in driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[5]'):
        Share.append(i.text)
except NoSuchElementException:
    Share.append("_")
    
# scraping GDP $ billion
try:
    for i in driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[6]'):
        GDP_billion.append(i.text)
except NoSuchElementException:
    GDP_billion.append("_")
    
    
# creating DataFrame from the scraped data
GDP = pd.DataFrame({'Rank':Rank,'State':State,'GSDP at current price (19-20)':GSDP1,'GSDP at current price (18-19)':GSDP2,'Share (18-19)':Share,'GDP($ billion)':GDP_billion})

GDP

In [ ]:
driver.close()

# 5 : Scrape the details of trending repositories on Github.com.

In [77]:
#getting url
url='https://github.com/'
# opening url
given_url(url)

In [ ]:
# getting explore button and clicking on it
explore = driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary').click()

# selecting trending option
trend_url = driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul[2]/li[3]/a")
urls = trend_url.get_attribute("href")
driver.get(urls)

In [ ]:
# creating empty list
URLs = []
repository_title = []
Description = []
Contributors = []
Language = []
lang = []

# fetching urls for each repository
repository = driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']//a")
for i in repository:
    URLs.append(i.get_attribute("href"))
    
# scraping Repository title data
title = driver.find_elements_by_xpath("//h1[@class = 'h3 lh-condensed']")
for i in title:
    repository_title.append(i.text)
    
# scraping data from all repository page
for i in URLs:
    driver.get(i)
    time.sleep(5)
    
    # scraping Repository Description data 
    try:
        desc = driver.find_element_by_xpath("//p[@class='f4 mt-3']")
        Description.append(desc.text)
    except NoSuchElementException:
        Description.append('-')
        
        
    # scraping Contributors Count data
    try:
        contributor = driver.find_element_by_xpath("//*[contains(text(),'    Contributors ')]")
        Contributors.append(contributor.text.replace('Contributors',''))
    except NoSuchElementException:
        Contributors.append('-')
    
    
    # scraping Languages used data
    try:
        for i in driver.find_elements_by_xpath("//ul[@class= 'list-style-none']//li//span[1]"):
            lang.append(i.text)
        Language.append(lang)
    except NoSuchElementException:
        Language.append('-')
        
        
# Data Framing
df= pd.DataFrame({'Repository Title': repository_title,'Repository Description': Description,'Contributors Count':Contributors,'Language Used':Language})
df

In [ ]:
driver.close()

# 6. Scrape the details of top 100 songs on billiboard.com.

In [ ]:
#getting url
url = 'https:/www.billboard.com/'
# opening url
given_url(url)
# clicking on option button
charts=driver.find_element(By.XPATH,"//a[@class='header__main-link header__main-link--charts']").click()

view_chart=driver.find_element(By.XPATH,'//div[@class="lrv-u-flex lrv-u-justify-content-center"]')

In [ ]:
# creating empty lists
Song_Name = []
Artist_Name =[]
Last_week_rank = []
Peak_rank = []
Weeks_on_board = []

# getting urls for top 100 songs
urls = driver.find_element(By.XPATH,"//li[@class='header__submenu__list__element']//a")
page_url = urls.get_attribute("href")
driver.get(page_url)
time.sleep(4)

# scraping data of song names
for i in driver.find_elements(By.XPATH,"//span[@class='chart-element__information__song text--truncate color--primary']"):
    Song_Name.append(i.text)
    
# scraping data of artist names
for i in driver.find_elements(By.XPATH,"//span[@class='chart-element__information__artist text--truncate color--secondary']"):
    Artist_Name.append(i.text)
    
# scraping data of last week ranks
for i in driver.find_elements(By.XPATH,"//div[@class='chart-element__meta text--center color--secondary text--last']"):
    Last_week_rank.append(i.text)
    

# scraping data of peak ranks
for i in driver.find_elements(By.XPATH,"//div[@class='chart-element__meta text--center color--secondary text--peak']"):
    Peak_rank.append(i.text)       
    
    
# scraping data of weeks on board
for i in driver.find_elements(By.XPATH,"//div[@class='chart-element__meta text--center color--secondary text--week']"):
    Weeks_on_board.append(i.text)
    
#printing length
print(len(Song_Name),len(Artist_Name),len(Last_week_rank),len(Peak_rank),len(Weeks_on_board))

#creating dataframe
df=pd.DataFrame({'Song_Name':Song_Name,'Artist_Name':Artist_Name,'Last_week_rank':Last_week_rank,'Peak_rank':Peak_rank,'Weeks_on_board':Weeks_on_board})
df

In [ ]:
driver.close()

# 7 Scrape the details of Data science recruiters from naukri.com.

In [48]:
# getting the webpage of mentioned url
url = "https://www.naukri.com/hr-recruiters-consultants"
# opening url
given_url(url)

# fetching search button, sending keys and clicking on it
recruiter = driver.find_element(By.XPATH,'//input[@class="sugInp"]')
recruiter.send_keys("Data Science")

search = driver.find_element(By.XPATH,'//button[@class="fl qsbSrch blueBtn"]').click()
#time.sleep(3)

# creating empty lists
Name = []
Designation = []
Company = []
Skills = []
Location = []

# scraping data of Names
for i in driver.find_elements(By.XPATH,'//span[@class="fl ellipsis"]'):
    Name.append(i.text)
    



# scraping data of Designation
for i in driver.find_elements(By.XPATH,'//span[@class="ellipsis clr"]'):
    Designation.append(i.text)
    


# scraping data of Company Name
for i in driver.find_elements(By.XPATH,'//a[@class="ellipsis"]'):
    Company.append(i.text)
    



# scraping data of Skills
for i in driver.find_elements(By.XPATH,'//div[@class="hireSec highlightable"]'):
    try:
        if i.text == "Not Specified": raise NoSuchElementException
        Skills.append(i.text)
    except NoSuchElementException:
        Skills.append('-')
        



# scraping data of Location
for i in driver.find_elements(By.XPATH,'//small[@class="ellipsis"]'):
    try:
        if i.text == "Not Specified": raise NoSuchElementException
        Location.append(i.text)
    except NoSuchElementException:
        Location.append('-')

In [54]:
# creating dataframe for scraped data
Naukri = pd.DataFrame({'Name':Name[:47],'Designation':Designation[:47],'Company':Company[:47],'Skills':Skills[:47],'Location':Location[:47]})
Naukri

,Name,Designation,Company,Skills,Location
0,Aakash Harit,HR Manager,Aakash Harit,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Data Science Network,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,shravan Kumar Gaddam,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Shore Infotech India Pvt. Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,MARSIAN Technologies LLP,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,MARSIAN Technologies LLP,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,Anik Agrawal,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Enerlytics Software Solutions Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Director,subhas patel,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,Human Resource,LibraryXProject,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Kalpana Dumpala,Executive Hiring,Abhishek - Only Analytics Hiring - India and,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
11,Mubarak,Company HR,Apidel Technologies Division of Transpower,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
12,Kushal Rastogi,Company HR,Institute for Financial Management and Resear,"Office Administration, Hr Administration, tele...",Mumbai
13,Mahesh Babu Channa,HR Team Lead,IFMR,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
14,Vaishnavi Kudalkar,HR Executive,Balu Ramesh,"Data Science, Python, Data Analytics",Mumbai
15,Priyanka Akiri,HR Manager,Techvantage Systems Pvt Ltd,"Oracle Dba, Data Science, Data Warehousing, ET...",Hyderabad
16,Kapil Devang,HR Manager,Asif Lucknowi,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
17,Sakshi Chhikara,Assistant Manager HR,Weupskill- Live Wire India,"React.js, Data Science, Java, Front End, Busin...",Chandigarh
18,Ruchi Dhote,Senior Executive Talent Acquisition,InstaFinancials,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
19,Manisha Yadav,HR Executive,CBL Data Science Private Limited,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
20,Riya Rajesh,Manager Talent Acquisition,Kalpana Dumpala,Data Science,Cochin
21,Rashmi Bhattacharjee,HR Head,Innominds Software,"Corporate Sales, Software Development, Softwar...",Delhi
22,Faizan Kareem,HR MANAGER,Mubarak,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
23,Rithika dadwal,HR Recruiter,MoneyTap,"Data Science, Machine Learning, Python, R, Dee...",Pune
24,Sandhya Khandagale,HR Recruiter,Kushal Rastogi,"Big Data, Data Science, Artificial Intelligenc...",Pune
25,Shaun Rao,Manager Human Resources,QuantMagnum Technologies Pvt. Ltd.,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
26,Deeparchi Sharma,Company Recruiter,Mahesh Babu Channa,"Research, Digital Marketing, Analytics, Softwa...",Gurgaon
27,Azahar Shaikh,Company Recruiter,SocialPrachar.com,"Data Science, Artificial Intelligence, Machine...",Pune
28,Manas,Lead Talent acquisition,Vaishnavi Kudalkar,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
29,kumar,Proprietor,Codeachive learning,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
30,Sunil Vedula,CEO,Priyanka Akiri,"Signal Processing, Machine Learning, Neural Ne...",Delhi
31,Rajat Kumar,Founder CEO,Infinitive Software Solutions,"Web Technologies, Project Management, Software...",Bengaluru / Bangalore
32,Dhruv Dev Dubey,Company Recruitment Head,Kapil Devang,"Server Administartion, Verilog, Vhdl, Digital ...",Mysoru / Mysore
33,Jayanth N,Project Manager,BISP Solutions,"Data Analytics, Managed Services, Team Leading...",Hyderabad / Secunderabad
34,Avodha,Business Development Associate,Sakshi Chhikara,"Ethical Hacking, Security Operations Center, S...",Bengaluru / Bangalore
35,Priya Khare,Senior Manager,BIZ INFOTECNO PRIVATE LIMITED,"Data Science, Artificial Intelligence, analyti...",New Delhi
36,Amit Sharma,Consultant,Ruchi Dhote,"Machine Learning, Artificial Intelligence, Dat...",Chennai
37,Kanan,senior technology instructor,Bristlecone India Ltd,"C, C++, Artificial Intelligence, Python, Php, ...",Aligarh
38,Shashikant Chaudhary,HR Recruiter/HR Excutive,Manisha Yadav,"Relationship Management, Retail Sales, Private...",Salt Lake City
39,Brad,"Manager, Technical Recruiting",Easi Tax,"Data Science, Software Engineering",Pune
40,Rutuja Pawar,Technical Recruiter,Riya Rajesh,"Data Science, Big Data Analytics, Digital Mark...",Bengaluru / Bangalore
41,Madhusudhan Sridhar,Erp Implementer,Novelworx Digital Solutions,"Data Science, Recruitment, Salary",Mumbai
42,Ankit Sinha,Head Analytics,Rashmi Bhattacharjee,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Indore
43,Gaurav Chouhan,Chief Technical Officer,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Software Development, Business Intelligence, B...",Bengaluru / Bangalore
44,Rashi Kacker,Sr Product Manager,Faizan Kareem,"Data Science, Node.js, Angularjs",MYSORE
45,Ashwini,Director Global Delivery,FirstTech Consaltants Pvt.Ltd,"Data Science, Media Marketing, Resource Planni...",Hyderabad / Secunderabad
46,Balaji Kolli,Co Founder,Rithika dadwal,"Data Analysis, Learning, Data Science, Compute...",Bengaluru / Bangalore

In [55]:
driver.close()

# 8. scrap deatils of highest selling novel

In [57]:
url='https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare'
# opening url
given_url(url)
#creating a blank list 
Rank=[]
Book=[]
Author=[]
Volumes_sold=[]
Publisher=[]
Genre=[]

# get web elements
rank_wbe = driver.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[1]")
for i in rank_wbe:
    Rank.append(i.text)
bname_wbe = driver.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[2]")
for i in bname_wbe:
    Book.append(i.text)
auth_name_wbe = driver.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[3]")
for i in auth_name_wbe:
    Author.append(i.text)

vols_sold_wbe = driver.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[4]")
for i in vols_sold_wbe:
    Volumes_sold.append(i.text)
publisher_wbe = driver.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[5]")
for i in publisher_wbe:
    Publisher.append(i.text)
genre_wbe = driver.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[6]")
for i in genre_wbe:
    Genre.append(i.text)

In [58]:
#printing length
print(len(Rank),len(Book),len(Author),len(Volumes_sold),len(Publisher),len(Genre))

100 100 100 100 100 100

In [59]:
#creating dataframe
df=pd.DataFrame({'Rank':Rank,'Book name':Book,'Volumes_sold':Volumes_sold,'Publisher':Publisher,'Genre':Genre})
df

,Rank,Book name,Volumes_sold,Publisher,Genre
0,1,"Da Vinci Code,The","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,2,Harry Potter and the Deathly Hallows,"4,475,152",Bloomsbury,Children's Fiction
2,3,Harry Potter and the Philosopher's Stone,"4,200,654",Bloomsbury,Children's Fiction
3,4,Harry Potter and the Order of the Phoenix,"4,179,479",Bloomsbury,Children's Fiction
4,5,Fifty Shades of Grey,"3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,96,"Ghost,The","807,311",Random House,General & Literary Fiction
96,97,Happy Days with the Naked Chef,"794,201",Penguin,Food & Drink: General
97,98,"Hunger Games,The:Hunger Games Trilogy","792,187",Scholastic Ltd.,Young Adult Fiction
98,99,"Lost Boy,The:A Foster Child's Search for the L...","791,507",Orion,Biography: General
99,100,Jamie's Ministry of Food:Anyone Can Learn to C...,"791,095",Penguin,Food & Drink: General

In [60]:
driver.close()

# 9. Scrape the details most watched tv series of all time from imdb.com.

In [61]:
url='https://www.imdb.com/list/ls095964455/'
#opening url
given_url(url)
#creating a blank list
Name=[]
Year_span=[]
Genre=[]
Run_time=[]
Ratings=[]
Votes=[]
# getting weeb element
name=driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/h3/a')
for i in name:
    Name.append(i.text)
    
yr=driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/h3/span[2]')
for i in yr:
    Year_span.append(i.text)
    
genre=driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/p[@class="text-muted text-small"]/span[@class="genre"]')
for i in genre:
    Genre.append(i.text)
    
run=driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/p[@class="text-muted text-small"]/span[@class="runtime"]')
for i in run:
    Run_time.append(i.text)
    
rating=driver.find_elements(By.XPATH,'//div[@class="ipl-rating-star small"]/span[@class="ipl-rating-star__rating"]')
for i in rating:
    Ratings.append(i.text)
    
votes=driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/p[@class="text-muted text-small"]/span[@name="nv"]')
for i in votes:
    Votes.append(i.text)

In [62]:
# printing length
print(len(Name),len(Year_span),len(Genre),len(Run_time),len(Ratings),len(Votes))

100 100 100 100 100 100

In [63]:
#creating dataframe
df=pd.DataFrame({'Name':Name,'Year_span':Year_span,'Genre':Genre,'Run_time':Run_time,'Ratings':Ratings,'Votes':Votes})
df

,Name,Year_span,Genre,Run_time,Ratings,Votes
0,Game of Thrones,(2011â€“2019),"Action, Adventure, Drama",57 min,9.2,"2,100,183"
1,Stranger Things,(2016â€“ ),"Drama, Fantasy, Horror",51 min,8.7,"1,190,448"
2,The Walking Dead,(2010â€“2022),"Drama, Horror, Thriller",44 min,8.1,"994,199"
3,13 Reasons Why,(2017â€“2020),"Drama, Mystery, Thriller",60 min,7.5,"294,235"
4,The 100,(2014â€“2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"253,338"
...,...,...,...,...,...,...
95,Reign,(2013â€“2017),Drama,42 min,7.4,"50,377"
96,A Series of Unfortunate Events,(2017â€“2019),"Adventure, Comedy, Drama",50 min,7.8,"61,986"
97,Criminal Minds,(2005â€“ ),"Crime, Drama, Mystery",42 min,8.1,"199,943"
98,Scream: The TV Series,(2015â€“2019),"Comedy, Crime, Drama",45 min,7.1,"41,715"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"246,996"

In [64]:
driver.close()

# 10. scrap the details of Datasets from UCI machine learning repositories.

In [74]:
# giving url
url = 'https://archive.ics.uci.edu/'

#opening url
given_url(url)

#click on "view all repositories"
driver.find_element(By.XPATH,'/html/body/table[1]/tbody/tr/td[2]/span[2]/a').click()

#creating a blank list

Dataset_name=[]
Data_type=[]
Task=[]
Attribute_type=[]
No_of_instances=[]
No_of_attribute=[]
Year=[]

#getting webelements
name=driver.find_elements(By.XPATH,'//span[@class="heading"]')
for i in name:
    Dataset_name.append(name.text)
    
data=driver.find_elements(By.XPATH,'//table[@border="1"]//tbody/tr/td[2]')
for i in name:
    Data_type.append(data.text)
    
task=driver.find_elements(By.XPATH,'//table[@border="1"]//tbody/tr[3]/td[2]')
for i in name:
    Task.append(task.text)
    
attribute=driver.find_elements(By.XPATH,'//table[@border="1"]//tbody/tr[2]/td[2]')
for i in name:
    Attribute_type.append(attribute.text)
    
inst=driver.find_elements(By.XPATH,'//table[@border="1"]//tbody/tr/td[4]')
for i in name:
    No_of_instances.append(inst.text)
    
atr=driver.find_elements(By.XPATH,'//table[@border="1"]//tbody/tr[2]/td[4]')
for i in name:
    No_of_attribute.append(atr.text)
    
year=driver.find_elements(By.XPATH,'//table[@border="1"]//tbody/tr[2]/td[6]')
for i in name:
    Year.append(year.text)

In [ ]:
#printing length
print(len(Dataset_name),len(Data_type),len(Task),len(Attribute_type),len(No_of_instances),len(No_of_attribute),len(Year))

In [ ]:
#creating a dataframe
df=pd.DataFrame({'Dataset_name':Dataset_name,'Data_type':Data_type,'Task':Task,'Attribute_type':Attribute_type,'No_of_instances':No_of_instances,'No_of_attribute':No_of_attribute,'Year':Year})
df